### ISSUE TITLE
IREE: 'tensor.empty' op dynamic sizes unexpected

### ISSUE THREAD

**Issue by njsharpe** [nod-ai/SHARK#887]
### Environment:
Windows 10 21H2
AMD Radeon 6700XT (12 GB VRAM)
Python 3.10.6

### Problem:
With the latest version of the GitHub repo as of the time of this post, I get a new, unexpected error when using a custom `.ckpt` file, in this case AbyssOrangeMix2. The executed command is as follows: `python ../shark/examples/shark_inference/stable_diffusion/main.py --precision="%precision%" --steps="%steps%" --max_length="%length%" --prompts="%prompts%" --negative-prompts="%negative_prompts%" --seed="%seed%" --ckpt_loc="%ckpt%" --guidance_scale="%cfg_scale%" --runs="%iterations%" --output_dir="generated_imgs" --iree-vulkan-target-triple="rdna2-unknown-windows" --warmup_count="%warmup%" --no-progress_bar --device="vulkan://0" --scheduler="%scheduler%" --annotation_model="vae" --enable_stack_trace --import_mlir`, where all variables are defined explicitly within a larger script. The inputs to those variables are printed at the start of the output below.

Despite some knowledge on the subject, I could not figure this one out.

```
Generating 1 image(s) with the following settings:
        Checkpoint:     ao2
        Scheduler:      SharkEulerDiscrete
        CFG:            11
        Steps:          20
        Length:         77
        Precision:      fp32
        Warmup:         25
        Seed:           317451943324425

shark_tank local cache is located at C:\Users\nelso\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Running StableDiffusion with the following config :-
Batch size : 1
Prompts : ['(masterpiece), (best quality), perfect face, beautiful shadows, detailed eyes, 1girl, black sports bra and panties, skinny, medium breasts, bright red hair, medium hair, yellow eyes, monochrome dark skin, underboob, full body, in hell, lava, detailed background']
Runs : 1
Found device AMD Radeon RX 6700 XT. Using target triple rdna2-unknown-windows.
Tuned models are currently not supported for this setting.
Traceback (most recent call last):
  File "D:\Stable\stable-diffusion-shark\shark\examples\shark_inference\stable_diffusion\model_wrappers.py", line 224, in __call__
    compiled_unet = self.get_unet()
  File "D:\Stable\stable-diffusion-shark\shark\examples\shark_inference\stable_diffusion\model_wrappers.py", line 172, in get_unet
    shark_unet = compile_through_fx(
  File "D:\Stable\stable-diffusion-shark\shark\examples\shark_inference\stable_diffusion\utils.py", line 89, in compile_through_fx
    mlir_module, func_name = import_with_fx(
  File "D:\Stable\stable-diffusion-shark\shark\shark_importer.py", line 373, in import_with_fx
    fx_g = make_fx(
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 702, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 440, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 778, in trace
    (self.create_arg(fn(*args)),),
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 456, in wrapped
    out = f(*tensors)
  File "<string>", line 1, in <lambda>
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 756, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 406, in call_module
    return forward(*args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 749, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark\examples\shark_inference\stable_diffusion\model_wrappers.py", line 159, in forward
    unet_out = self.unet.forward(
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 481, in forward
    sample, res_samples = downsample_block(
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 756, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 406, in call_module
    return forward(*args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 749, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 789, in forward
    hidden_states = attn(
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 756, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 406, in call_module
    return forward(*args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 749, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\diffusers\models\transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 756, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 406, in call_module
    return forward(*args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 749, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\diffusers\models\attention.py", line 307, in forward
    attn_output = self.attn2(
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 756, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 406, in call_module
    return forward(*args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 749, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\diffusers\models\cross_attention.py", line 160, in forward
    return self.processor(
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\diffusers\models\cross_attention.py", line 234, in __call__
    key = attn.to_k(encoder_hidden_states)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 756, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 406, in call_module
    return forward(*args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\_symbolic_trace.py", line 749, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\nn\modules\module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\utils\_stats.py", line 15, in wrapper
    return fn(*args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 484, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 509, in inner_torch_dispatch
    out = proxy_call(self, func, args, kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\fx\experimental\proxy_tensor.py", line 342, in proxy_call
    out = func(*args, **kwargs)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x1024 and 768x320)
Retrying with a different base model configuration
D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\jit\_check.py:181: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
No vmfb found. Compiling and saving to D:\Stable\stable-diffusion-shark\web\unet1_77_512_512_fp32_ao2_vulkan-00000000-5500-0000-0000-000000000000.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\Stable\stable-diffusion-shark\web\unet1_77_512_512_fp32_ao2_vulkan-00000000-5500-0000-0000-000000000000.vmfb.
No vmfb found. Compiling and saving to D:\Stable\stable-diffusion-shark\web\vae1_77_512_512_fp32_ao2_vulkan-00000000-5500-0000-0000-000000000000.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Traceback (most recent call last):
  File "D:\Stable\stable-diffusion-shark\shark\examples\shark_inference\stable_diffusion\model_wrappers.py", line 225, in __call__
    compiled_vae = self.get_vae()
  File "D:\Stable\stable-diffusion-shark\shark\examples\shark_inference\stable_diffusion\model_wrappers.py", line 133, in get_vae
    shark_vae = compile_through_fx(
  File "D:\Stable\stable-diffusion-shark\shark\examples\shark_inference\stable_diffusion\utils.py", line 116, in compile_through_fx
    return _compile_module(shark_module, model_name, extra_args)
  File "D:\Stable\stable-diffusion-shark\shark\examples\shark_inference\stable_diffusion\utils.py", line 43, in _compile_module
    path = shark_module.save_module(
  File "D:\Stable\stable-diffusion-shark\shark\shark_inference.py", line 186, in save_module
    return export_iree_module_to_vmfb(
  File "D:\Stable\stable-diffusion-shark\shark\iree_utils\compile_utils.py", line 323, in export_iree_module_to_vmfb
    flatbuffer_blob = compile_module_to_flatbuffer(
  File "D:\Stable\stable-diffusion-shark\shark\iree_utils\compile_utils.py", line 270, in compile_module_to_flatbuffer
    flatbuffer_blob = ireec.compile_str(
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\iree\compiler\tools\core.py", line 278, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\iree\compiler\tools\binaries.py", line 196, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile.exe
Diagnostics:
<eval_with_key>.5:11:20: error: 'tensor.empty' op incorrect number of dynamic sizes, has 0, expected 4
<unknown>:0: error: Failures have been detected while processing an MLIR pass pipeline
<unknown>:0: note: Pipeline failed while executing [`ConvertConvNchwToNhwc` on 'func.func' operation: @forward]: reproducer generated at `iree_temp\core-reproducer.mlir`


Invoked with:
 iree-compile.exe D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\iree\compiler\tools\..\_mlir_libs\iree-compile.exe - --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --iree-llvm-embedded-linker-path=D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\iree\compiler\tools\..\_mlir_libs\iree-lld.exe --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --mlir-pass-pipeline-crash-reproducer=iree_temp\core-reproducer.mlir --iree-llvm-target-cpu-features=host --iree-vulkan-target-env=#vk.target_env<v1.3, r(120), [VK_KHR_16bit_storage, VK_KHR_8bit_storage, VK_KHR_shader_float16_int8, VK_KHR_spirv_1_4, VK_KHR_storage_buffer_storage_class, VK_KHR_variable_pointers, VK_EXT_subgroup_size_control], AMD:DiscreteGPU, #vk.caps< maxComputeSharedMemorySize = 65536, maxComputeWorkGroupInvocations = 1024, maxComputeWorkGroupSize = dense<[1024, 1024, 1024]>: vector<3xi32>, subgroupSize = 64, subgroupFeatures = 255: i32, minSubgroupSize = 32, maxSubgroupSize = 64, shaderFloat16 = unit, shaderFloat64 = unit, shaderInt8 = unit, shaderInt16 = unit, shaderInt64 = unit, storageBuffer16BitAccess = unit, storagePushConstant16 = unit, uniformAndStorageBuffer16BitAccess = unit, storageBuffer8BitAccess = unit, storagePushConstant8 = unit, uniformAndStorageBuffer8BitAccess = unit, variablePointers = unit, variablePointersStorageBuffer = unit >> --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs -iree-vulkan-target-triple=rdna2-unknown-windows --iree-flow-enable-conv-nchw-to-nhwc-transform --iree-flow-enable-padding-linalg-ops --iree-flow-linalg-ops-padding-size=16

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.

Deleted:  D:\Stable\stable-diffusion-shark\web\unet1_77_512_512_fp32_ao2_vulkan-00000000-5500-0000-0000-000000000000.vmfb
Retrying with a different base model configuration
Cannot compile the model. Please use `enable_stack_trace` and create an issue at https://github.com/nod-ai/SHARK/issues
Press any key to continue . . .
```

Edit: Included information from IREE_SAVE_TEMPS enabled.

**Comment by njsharpe** [comment]
On a related note, I did install the following additional packages: `accelerate, safetensors, omegaconf, pytorch_lightning`.

**Comment by ForserX** [comment]
+1
For all .ckpt and .safetensors files

**Comment by Abhishek-Varma** [comment]
Hi @njsharpe @ForserX 

1. Please pull in latest `main` branch of SHARK.
2. Blow up `shark.venv`.
3. Build `shark.venv` using the script `setup_ven..`.
4. For custom checkpoint execution run :
```
python apps/stable_diffusion/scripts/txt2img.py --clear_all --precision=fp16 --device=vulkan --prompt="tajmahal, oil on canvas, sunflowers, 4k, uhd" --max_length=64 --import_mlir --ckpt_loc="/home/user/AbyssOrangeMix2.ckpt" --no-use_tuned --enable_stack_trace
```
5. For running HuggingFace repo run :
```
python apps/stable_diffusion/scripts/txt2img.py --clear_all --precision=fp16 --device=vulkan --prompt="tajmahal, oil on canvas, sunflowers, 4k, uhd" --max_length=64 --import_mlir --no-use_tuned --enable_stack_trace --hf_model_id="WarriorMama777/OrangeMixs"
```

**Comment by njsharpe** [comment]
When running a custom checkpoint, I get the following error:
```
(shark.venv) PS D:\Stable\stable-diffusion-shark> python apps/stable_diffusion/scripts/txt2img.py --clear_all --precision=fp16 --device=vulkan --prompt="tajmahal, oil on canvas, sunflowers, 4k, uhd" --max_length=64 --import_mlir --ckpt_loc="ckpt/ao2.ckpt" --no-use_tuned --enable_stack_trace
shark_tank local cache is located at C:\Users\nelso\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
CLEARING ALL, EXPECT SEVERAL MINUTES TO RECOMPILE
Found device AMD Radeon RX 6700 XT. Using target triple rdna2-unknown-windows.
Tuned models are currently not supported for this setting.
D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\torch\jit\_check.py:172: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
No vmfb found. Compiling and saving to D:\Stable\stable-diffusion-shark\euler_scale_model_input_1_512_512fp16_vulkan-00000000-5500-0000-0000-000000000000.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\Stable\stable-diffusion-shark\euler_scale_model_input_1_512_512fp16_vulkan-00000000-5500-0000-0000-000000000000.vmfb.
No vmfb found. Compiling and saving to D:\Stable\stable-diffusion-shark\euler_step_1_512_512fp16_vulkan-00000000-5500-0000-0000-000000000000.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in D:\Stable\stable-diffusion-shark\euler_step_1_512_512fp16_vulkan-00000000-5500-0000-0000-000000000000.vmfb.
Created directory :  ao2  at ->  D:\Stable\stable-diffusion-shark\ckpt
Loading pipeline from original stable diffusion checkpoint
global_step key not found in model
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
--2023-02-02 18:03:19--  https://raw.githubusercontent.com/CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml
Resolving raw.githubusercontent.com... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com|185.199.110.133|:443... connected.
Unable to establish SSL connection.
Traceback (most recent call last):
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\scripts\txt2img.py", line 243, in <module>
    txt2img_obj = Text2ImagePipeline.from_pretrained(
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 193, in from_pretrained
    ckpt_loc = preprocessCKPT()
  File "D:\Stable\stable-diffusion-shark\apps\stable_diffusion\src\utils\utils.py", line 387, in preprocessCKPT
    pipe = load_pipeline_from_original_stable_diffusion_ckpt(
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 887, in load_pipeline_from_original_stable_diffusion_ckpt
    "parameterization" in original_config["model"]["params"]
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\omegaconf\dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\omegaconf\_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\omegaconf\dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\omegaconf\dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\omegaconf\basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "D:\Stable\stable-diffusion-shark\shark.venv\lib\site-packages\omegaconf\dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigKeyError: Missing key model
    full_key: model
    object_type=dict
```
I did need to manually add `wget` to my path.

**Comment by Abhishek-Varma** [comment]
Hi @njsharpe

1. `wget` issue has been resolved as [part of diffusers](https://github.com/huggingface/diffusers/pull/2168) but we've to wait for it to be rolled out in diffusers' next [release](https://github.com/huggingface/diffusers/releases/). So yes, currently it needs to be added in the PATH.

2. For working with AbyssOrangeMix checkpoint files - can you please try out the checkpoints from the following :-
    - [AbyssOrangeMix2_hard.safetensors](https://huggingface.co/WarriorMama777/OrangeMixs/resolve/main/Models/AbyssOrangeMix2/AbyssOrangeMix2_hard.safetensors)
    - [AbyssOrangeMix2_nsfw.safetensors](https://huggingface.co/WarriorMama777/OrangeMixs/resolve/main/Models/AbyssOrangeMix2/AbyssOrangeMix2_nsfw.safetensors)
    - [AbyssOrangeMix2_sfw.ckpt](https://huggingface.co/WarriorMama777/OrangeMixs/resolve/main/Models/AbyssOrangeMix2/AbyssOrangeMix2_sfw.ckpt)
    - [AbyssOrangeMix2_sfw.safetensors](https://huggingface.co/WarriorMama777/OrangeMixs/resolve/main/Models/AbyssOrangeMix2/AbyssOrangeMix2_sfw.safetensors)

I see this issue being raised by few others - quite likely the checkpoint file you're using has got nothing to do with the issue but still trying to weed out the slightest possibility.

Do try following the steps mentioned earlier and see if you can use the checkpoint files attached in this thread for AbyssOrangeMix.
Let me know your findings.

**Comment by njsharpe** [comment]
@Abhishek-Varma, I used the linked provided to download all of the mentioned checkpoints. All of them produced the same error from my previous comment. I also noticed the project was updated but the same error still occurred after a `git pull` and a full clear of my python cache before running `./setup_venv.ps1`.

**Comment by njsharpe** [comment]
@Abhishek-Varma
I have found the culprit! As we know, the wget call at `diffusers/pipelines/stable_diffusion/convert_from_ckpt.py#876` uses the locally installed version of wget found in our PATH. It seems that @ForserX and I may have a faulty version of wget.

After installing [the correct version of wget](https://eternallybored.org/misc/wget/) and updating my PATH, the program works as intended.

```
prompt=['tajmahal, oil on canvas, sunflowers, 4k, uhd']
negative prompt=['']
model_id=CompVis/stable-diffusion-v1-4, ckpt_loc=web/models/AbyssOrangeMix2_sfw.safetensors
scheduler=SharkEulerDiscrete, device=vulkan://00000000-5500-0000-0000-000000000000
steps=50, guidance_scale=7.5, seed=42, size=512x512, batch size=1, max_length=64
Clip Inference time (ms) = 167.775
Average step time: 751.4156818389893ms/it
VAE Inference time (ms): 2611.858
Total image generation time: 40.4965sec
```

Closing as resolved.
